name: LuckyBlock
main: palente\luckyblock\Main
version: 0.8
author:
  - Palente
  # Can I ? - Bluzzi 
api: 3.0.0
softdepend: ["EconomyAPI", "PiggyCustomEnchants"]

description: "A Lucky Block Plugin by Palente"
website: "https://github.com/Palente/LuckyBlock"