name: LuckyBlock
version: "0.0.1"
author: Palente
main: Palente\LuckyBlock\Main
description: "a Lucky Block plugin by Palente"
website: "https://github.com/Palente"
depends: ["EconomyAPI"]
api: 
  - "3.0.0"
  - "3.0.2"
  - "4.0.0"